server:
  port: 9090

#DATABASE
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/content_db
    username: content_user
    password: content_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  application:
    name: content


  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

file:
  upload-dir: ./uploads
  base-url: http://localhost:9191

